name = "PopSimBase"
uuid = "e60d1b08-a48f-4b5c-9e89-ad4b39d64fb4"
authors = ["Peter Arndt <arndt@molgen.mpg.de> and contributors"]
version = "0.1.2"

[deps]
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
julia = "1.6"
